### ISSUE TITLE
Hiragana or Kanji

### ISSUE THREAD

**Issue by uhlhosting** [kaakaa/mattermost-emojigen#1]
Does this works with all chars available? I tried to run it with 2 Kanjis, it went without any display, it worked with hiragana. 

How does one remove generated emojis?

**Comment by kaakaa** [comment]
Thanks for your comments @uhlhosting!

> Does this works with all chars available? I tried to run it with 2 Kanjis, it went without any display, it worked with hiragana.

For now, only few Kanjis (e.g: `木`, `林`) can be used for emojis, but I don't understand exactly which kanjis can be used. 

![スクリーンショット 2019-05-20 14 46 49](https://user-images.githubusercontent.com/1453749/57999071-09c2d480-7b0f-11e9-980d-b65fcb8f46e9.png)

I'm sorry that this limitations has been written in only Japanese in [README.md](https://github.com/kaakaa/mattermost-emojigen#usage).

> (For Japanese) 平仮名は絵文字にできますが漢字はほんの一部のみ画像化できるようです（カタカナはダメ）。https://github.com/pbnjay/pixfont で漢字なども画像化できる方法があれば可能になるかもしれません。

And this limitation comes from the limitation of https://github.com/pbnjay/pixfont, so it is needed to know more about pbnjay/pixfont.

---

> How does one remove generated emojis?

You can remove generated emoji in "Custom Emoji" manually.

---

And this plugin is developed for old Mattermost plugin architecture, so may not work for latest Mattermost release.

**Comment by uhlhosting** [comment]
@kaakaa any plans to update it for new release architecture. Maybe it works only with main Kanjis, Japanese is a language or wonders. 

Domo arigato gozaimasu

**Comment by kaakaa** [comment]
Updated emojigen plugin to `v0.1.0` for new Mattemrost plugin architecture. 
https://github.com/kaakaa/mattermost-emojigen/releases/tag/v0.1.0

I tested this on Mattemrost 5.10, and it works fine for me.

> Maybe it works only with main Kanjis, Japanese is a language or wonders.

Could be... Since Japanese (or Kanjis) has some complexity, it may be hard to support all characters. I'll take a look into `pbnjay/pixfont`.

> Domo arigato gozaimasu

どういたしまして! 😄  (You're welcome!)

**Comment by kaakaa** [comment]
@uhlhosting 
I've released [v0.2.0](https://github.com/kaakaa/mattermost-emojigen/releases/tag/v0.2.0).
It uses [`M+ Fonts`](https://mplus-fonts.osdn.jp/about-en.html) for generating emoji instead of `pbnjay/pixfont`, and can generate most of Japanese characters including Kanjis. (but it might not generate Chinese and Koreans...)

![スクリーンショット 2019-06-03 0 08 42](https://user-images.githubusercontent.com/1453749/58763295-d151da80-8593-11e9-84dc-982464e4294d.png)

If you have a time, please try [new version of `mattermost-emojigen`](https://github.com/kaakaa/mattermost-emojigen/releases/tag/v0.2.0)!

 I close this issue because I supposed that this issue have been resolve. But feel free to reopen this issue if you encountered any problem related to this issue.
Thanks.
